[build]
  command = "sed -i -e \"s/AUTH_USERNAME_PLACEHOLDER/${AUTH_USERNAME}/g\" -e \"s/AUTH_PASSWORD_PLACEHOLDER/${AUTH_PASSWORD}/g\" netlify.toml && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "AUTH_USERNAME_PLACEHOLDER:AUTH_PASSWORD_PLACEHOLDER"